# SPDX-License-Identifier: GPL-2.0
#
# Makefile for PCI Endpoint Support
#

obj-$(CONFIG_PCI_ENDPOINT_CONFIGFS)	+= pci-ep-cfs.o
obj-$(CONFIG_PCI_ENDPOINT)		+= pci-epc-core.o pci-epf-core.o\
					   pci-epc-mem.o functions/
obj-$(CONFIG_PCIE_ARMADA_DW_EP)	+= pcie-armada-dw-ep.o
